Rectangle rectangle1 = new Rectangle(3, 4);
Rectangle rectangle2 = new Rectangle(4, 4);
Console.WriteLine(rectangle1.GetArea());
Console.WriteLine(rectangle1.GetPerimeter());
Console.WriteLine(rectangle1.IsSquare());
Console.WriteLine(rectangle1.ToString());
Console.WriteLine(rectangle2.GetArea());
Console.WriteLine(rectangle2.GetPerimeter());
Console.WriteLine(rectangle2.IsSquare());
Console.WriteLine(rectangle2.ToString());
